//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomValidation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using CustomValidation.Common;

    public partial class Employee
    {
        public int Id { get; set; }

        [StringLength(10, MinimumLength =3)]
        [Required]
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$", ErrorMessage = "Please Enter lower and upper case Only")]
        public string Name { get; set; }
        public string Email { get; set; }

        [Compare("Email")]
        public string ConfirmEmail { get; set; }

        [Range(1,100)]
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }

        //[Range(typeof(DateTime),"01/01/2001","01/01/2020")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        //[DateRange("01/01/2030")]
        [CurrentDate]
        public Nullable<System.DateTime> HireDate { get; set; }
    }
}
